### ISSUE TITLE
Time stamp issue

### ISSUE THREAD

**Issue by Barmaley13** [eugmes/python-gdsii#1]
Hello Eugeniy,
I've been using your GDSII library to parse some GDSII files and I've been having some issues reading files because of poorly formatted time stamps in those GDSII files.
Clearly, it is not your code but poor quality of the input files.

Anyway, I modified this method to fix the issue.
https://github.com/eugmes/python-gdsii/blob/a8f3a0517af00a7e65ffddfaec080ce90a5dd306/gdsii/record.py#L509

Posting it here just in case you find it useful.

        if len(self.data) != 12:
            raise exceptions.DataSizeError(self.tag)

        try:
            mod_time = datetime(self.data[0] + 1900, *self.data[1:6])
            acc_time = datetime(self.data[0] + 1900, *self.data[7:12])
        except:
            mod_time = datetime.utcnow()
            acc_time = datetime.utcnow()

        return (mod_time, acc_time)

Thanks for writing this package and all the best!!!
Cheers,
Kirill

**Comment by eugmes** [comment]
I've fixed this back in 2012 by replacing those dates with `1900-01-01T00:00:00` (a030e914153eaf7027d0180c49e96c9c08f5001e). But somehow that version was not pushed to github. I've now merged that version to `master`.
