### ISSUE TITLE
How to get source code as of release 0.2.1 for license compliance

### ISSUE THREAD

**Issue by stevecj** [eugmes/python-gdsii#3]
I need to get a copy of the source code in order to be able to comply with the license, but I can't see how to get that for release 0.2.1.

There is no tag for release 0.2.1, and in settings.py at HEAD, the version number remains 0.2.

**Comment by eugmes** [comment]
It is here now: https://github.com/eugmes/python-gdsii/tree/release-0.2.1

It was not migrated to github somehow. I've merged the original branch now.

Thanks for letting me know.
